"""empty message

Revision ID: af406a14a5de
Revises: None
Create Date: 2019-05-10 14:57:59.321583

"""

# revision identifiers, used by Alembic.
revision = 'af406a14a5de'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### end Alembic commands ###
    op.create_table('number_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('sip', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_calls')
    ### end Alembic commands ###
